version: "2.2"
services:
  jenkins:
    image: jenkins:alpine
    ports:
     - "8083:8080"
     - "50000:50000"
    restart: always
    extra_hosts:
     - "regintern:192.168.99.100"
    volumes:
     - /DockerVolumes/jenkins_home2:/var/jenkins_home
    networks:
      - infraNet
networks:
  infraNet: