version: "2.1"
services:
  regintern:
    image: registry:2
    ports:
     - "5000:5000"
    restart: always
    volumes:
     - /DockerVolumes/registryData:/var/lib/registry
    networks:
      - infraNet
networks:
  infraNet:
  external: true